### ISSUE TITLE
Readme file

### ISSUE THREAD

**Issue by schnorr** [VNNikolaidis/nnlib2Rcpp#3]
Regarding the `README.md` file

- [ ] It may contain better markup to indicate the code lines that should be copy-pasted to install the package.
- [ ] A simple usage example with some R lines that indicate how to use the package with the different neural networks available

**Comment by VNNikolaidis** [comment]
Thank you for the comment. The R commands needed to install the package are now emphasized with a little better markup. 
As for the second comment (lack of an example), I added in README.md the command needed to open the package documentation in R. In this package documentation each function and class is already documented and accompanied by an example code “snippet”. I hope this is sufficient, let me know if otherwise.

**Comment by VNNikolaidis** [comment]
I hope the changes made were sufficient, so I am closing the issue
